java:
  gateways:
    default:
      listeners:
        default:
          bind: :25565
  servers:
    default:
      gateways:
        - default
      domains:
        - "*"
      address: example.com:25565
      overrideStatus:
        versionName: Infrared
        maxPlayerCount: 777777777
        playerCount: 2